<a href="https://colab.research.google.com/github/cahyaniriskialif-cn/UTS-DATA-MINING-2304020014/blob/main/UTS_DATA_MINING_2304020014.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Library

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

Library yang digunakan dalam penelitian ini meliputi pandas dan numpy untuk pengolahan serta manipulasi data, matplotlib dan seaborn untuk visualisasi data agar lebih mudah dipahami, serta library dari scikit-learn seperti train_test_split untuk membagi data menjadi data pelatihan dan pengujian, RandomForestClassifier untuk membangun model klasifikasi dalam memprediksi kualitas wine, serta accuracy_score dan classification_report yang digunakan untuk mengevaluasi kinerja model berdasarkan tingkat akurasi, precision, recall, dan f1-score.

Load data

In [ ]:
train = pd.read_csv('/content/data_training.csv')
test = pd.read_csv('/content/data_testing.csv')

Kode ini digunakan untuk **membaca dan memuat dataset ke dalam program** agar bisa dianalisis dan diproses lebih lanjut. Secara khusus, `pd.read_csv()` berfungsi untuk membaca file berformat CSV, di mana data training dimuat ke dalam variabel **train** dan data testing dimuat ke dalam variabel **test**, sehingga keduanya dapat digunakan dalam tahap preprocessing, pembuatan model, hingga prediksi.

In [ ]:
train.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.3,0.740,0.08,1.7,0.094,10.0,45.0,0.99576,3.24,0.50,9.8,5,1366
1,8.1,0.575,0.22,2.1,0.077,12.0,65.0,0.99670,3.29,0.51,9.2,5,103
2,10.1,0.430,0.40,2.6,0.092,13.0,52.0,0.99834,3.22,0.64,10.0,7,942
3,12.9,0.500,0.55,2.8,0.072,7.0,24.0,1.00012,3.09,0.68,10.9,6,811
4,8.4,0.360,0.32,2.2,0.081,32.0,79.0,0.99640,3.30,0.72,11.0,6,918

Fungsi `train.head()` digunakan untuk **menampilkan beberapa baris pertama dari dataset training**. Secara default, fungsi ini akan menampilkan **5 baris teratas**, sehingga membantu pengguna untuk melihat struktur data, nama kolom, serta isi awal dataset sebagai langkah awal sebelum melakukan analisis lebih lanjut.

In [ ]:
test.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,Id
0,6.8,0.61,0.04,1.5,0.057,5.0,10.0,0.99525,3.42,0.60,9.500000,222
1,6.9,0.84,0.21,4.1,0.074,16.0,65.0,0.99842,3.53,0.72,9.233333,1514
2,7.0,0.58,0.12,1.9,0.091,34.0,124.0,0.99560,3.44,0.48,10.500000,417
3,7.8,0.48,0.68,1.7,0.415,14.0,32.0,0.99656,3.09,1.06,9.100000,754
4,12.5,0.60,0.49,4.3,0.100,5.0,14.0,1.00100,3.25,0.74,11.900000,516

Fungsi `test.head()` digunakan untuk **menampilkan beberapa baris pertama dari dataset testing**. Secara default, fungsi ini akan menampilkan **5 baris teratas**, sehingga membantu pengguna memahami struktur data testing, seperti nama kolom dan isi datanya, sebelum digunakan untuk proses prediksi.

Cek Struktur Data

In [ ]:
train.info()
train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 857 entries, 0 to 856
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         857 non-null    float64
 1   volatile acidity      857 non-null    float64
 2   citric acid           857 non-null    float64
 3   residual sugar        857 non-null    float64
 4   chlorides             857 non-null    float64
 5   free sulfur dioxide   857 non-null    float64
 6   total sulfur dioxide  857 non-null    float64
 7   density               857 non-null    float64
 8   pH                    857 non-null    float64
 9   sulphates             857 non-null    float64
 10  alcohol               857 non-null    float64
 11  quality               857 non-null    int64
 12  Id                    857 non-null    int64
dtypes: float64(11), int64(2)
memory usage: 87.2 KB

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000
mean,8.261960,0.529393,0.267351,2.506184,0.086830,15.782964,45.978413,0.996692,3.313092,0.656709,10.430338,5.653442,813.749125
std,1.701992,0.179162,0.195144,1.293512,0.048721,10.300402,31.692113,0.001901,0.152079,0.167364,1.066971,0.821777,463.807063
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.390000,8.400000,3.000000,0.000000
25%,7.100000,0.395000,0.090000,1.900000,0.070000,7.000000,21.000000,0.995520,3.210000,0.550000,9.500000,5.000000,413.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,14.000000,38.000000,0.996680,3.310000,0.620000,10.200000,6.000000,814.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,63.000000,0.997800,3.400000,0.730000,11.100000,6.000000,1214.000000
max,15.600000,1.580000,1.000000,15.500000,0.611000,68.000000,278.000000,1.003200,4.010000,2.000000,14.000000,8.000000,1597.000000

Fungsi train.info() digunakan untuk menampilkan informasi umum mengenai dataset seperti jumlah data, tipe data, serta keberadaan missing value, sedangkan train.describe() digunakan untuk menampilkan ringkasan statistik dari data numerik seperti nilai rata-rata, standar deviasi, nilai minimum, maksimum, dan kuartil, sehingga membantu dalam memahami karakteristik data sebelum dilakukan pemodelan.

Prepocessing (Pembersihan data)

1. Cek missing value

In [ ]:
print("Missing Train:\n", train.isnull().sum())
print("\nMissing Test:\n", test.isnull().sum())

Missing Train:
 fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

Missing Test:
 fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
Id                      0
dtype: int64

Kode ini digunakan untuk mengecek jumlah data yang hilang (missing value) pada setiap kolom di dataset training dan testing. Fungsi isnull() akan mendeteksi nilai yang kosong (NaN), kemudian sum() menghitung jumlahnya di tiap kolom, sehingga hasilnya menunjukkan berapa banyak data yang hilang pada masing-masing variabel. Perintah print() digunakan untuk menampilkan hasil tersebut dengan label “Missing Train” dan “Missing Test” agar lebih mudah dibedakan, sehingga dapat diketahui apakah data perlu dilakukan pembersihan sebelum proses pemodelan.Karena hasil output diperoleh semua variabel nilainya 0 maka tidak ada missing value dan dapat langsung dilanjutkan pada proses berikutnya.

In [ ]:
train = train.drop('Id', axis=1)
test_id = test['Id']  # simpan dulu buat nanti
test = test.drop('Id', axis=1)

Kode tersebut digunakan untuk menghapus kolom Id dari dataset training dan testing karena kolom tersebut tidak berpengaruh dalam proses pemodelan, serta menyimpan nilai Id dari data testing untuk digunakan kembali saat penyusunan hasil prediksi dalam format CSV.

2. Pisahkan fitur dan target

In [ ]:
X = train.drop('quality', axis=1)
y = train['quality']

Kode tersebut digunakan untuk memisahkan dataset menjadi variabel fitur dan target, di mana X berisi seluruh variabel independen yang digunakan sebagai input model dengan menghapus kolom quality, sedangkan y merupakan variabel dependen yang berisi nilai kualitas wine yang akan diprediksi.

3. Split data untuk evaluasi

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

Kode tersebut digunakan untuk membagi dataset menjadi data pelatihan dan data validasi, di mana 80% data digunakan untuk melatih model dan 20% sisanya digunakan untuk menguji performa model. Pembagian ini dilakukan secara acak dengan menggunakan parameter random_state=42 agar hasil pembagian tetap konsisten setiap kali dijalankan.
Parameter random_state=42 digunakan untuk memastikan bahwa proses pembagian data dilakukan secara konsisten setiap kali kode dijalankan. Nilai ini berfungsi sebagai seed dalam proses pengacakan data sehingga hasil pembagian antara data pelatihan dan validasi tidak berubah-ubah, meskipun angka yang digunakan sebenarnya bersifat bebas dan tidak memiliki makna khusus.

4. Buat dan Latih Model (Random Forest)

In [ ]:
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    class_weight ='balanced'
)

model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10, n_estimators=200,
                       random_state=42)

Kode ini digunakan untuk emmbuat dan melatih model Random Forest agar bisa belajar dari data training.
Kode tersebut digunakan untuk membangun model klasifikasi menggunakan algoritma Random Forest dengan 200 pohon keputusan dan batas kedalaman maksimal 10 untuk menghindari overfitting. Parameter class_weight='balanced' digunakan untuk menangani ketidakseimbangan data antar kelas, sedangkan random_state=42 memastikan hasil yang konsisten. Selanjutnya, fungsi fit() digunakan untuk melatih model menggunakan data pelatihan agar model dapat mempelajari pola hubungan antara fitur dan target.

5. Evaluasi model

In [ ]:
y_pred = model.predict(X_val)

print("Accuracy:", accuracy_score(y_val, y_pred))
print("\nClassification Report:\n", classification_report(y_val, y_pred))

Accuracy: 0.5755813953488372

Classification Report:
               precision    recall  f1-score   support

           4       0.00      0.00      0.00         3
           5       0.61      0.67      0.64        67
           6       0.57      0.56      0.57        78
           7       0.50      0.48      0.49        21
           8       0.00      0.00      0.00         3

    accuracy                           0.58       172
   macro avg       0.34      0.34      0.34       172
weighted avg       0.56      0.58      0.57       172

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Kode ini digunakan untuk melakukan prediksi pada data validasi dan mengevaluasi kinerja model dengan menghitung nilai akurasi serta menampilkan classification report yang berisi metrik precision, recall, dan f1-score untuk menilai performa model secara lebih rinci.

Latih ulang menggunakan seluruh data training

In [ ]:
model.fit(X, y)

RandomForestClassifier(class_weight='balanced', max_depth=10, n_estimators=200,
                       random_state=42)

Prediksi data testing

In [ ]:
test_pred = model.predict(test)

Digunakan untuk melakukan prediksi pada data testing menggunakan model yang sudah dilatih.Disini model menebak nilai quality berdasarkan fitur pada data testing, hasil pediksi akan disimpan ke variabel test_pred sehingga outputnya adalh hasil prediksi dari model.

In [ ]:
submission = pd.DataFrame({
    'id': test_id,
    'quality': test_pred
})

submission.to_csv('hasilprediksi_3NIM.csv', index=False)

Kode tersebut digunakan untuk menyusun dan menyimpan hasil prediksi model ke dalam format file CSV yang siap untuk dikumpulkan. Pertama, fungsi `pd.DataFrame()` digunakan untuk membuat sebuah tabel baru yang terdiri dari dua kolom, yaitu `id` yang berasal dari data testing sebagai identitas setiap data, dan `quality` yang merupakan hasil prediksi model terhadap kualitas wine. Selanjutnya, fungsi `to_csv()` digunakan untuk menyimpan DataFrame tersebut ke dalam file dengan nama `hasilprediksi_3NIM.csv`, di mana parameter `index=False` memastikan bahwa indeks tambahan tidak ikut disimpan dalam file, sehingga format file sesuai dengan ketentuan yang diminta, yaitu hanya berisi kolom `id` dan `quality`.

In [ ]:
submission.head()

     id  quality
0   222        5
1  1514        6
2   417        5
3   754        5
4   516        6

Fungsi submission.head() digunakan untuk menampilkan beberapa baris pertama dari DataFrame hasil prediksi, sehingga dapat dilakukan pengecekan awal terhadap struktur data, seperti kesesuaian nama kolom dan hasil prediksi, sebelum data disimpan ke dalam file CSV atau dikumpulkan.

In [ ]:
from google.colab import files
files.download('hasilprediksi_3NIM.csv')

Metode Decision Tree

In [ ]:
model = DecisionTreeClassifier(
    max_depth=10,
    random_state=42,
    class_weight='balanced'
)

Model klasifikasi Decision Tree dibuat menggunakan DecisionTreeClassifier. Parameter max_depth=10 digunakan untuk membatasi kedalaman pohon agar mengurangi risiko overfitting, sedangkan class_weight='balanced' digunakan untuk menangani ketidakseimbangan jumlah data antar kelas.

In [ ]:
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced', max_depth=10, random_state=42)

Fungsi fit() digunakan untuk melatih model Decision Tree menggunakan data training (X_train dan y_train) agar model dapat mempelajari pola hubungan antara fitur dan target.

In [ ]:
y_pred = model.predict(X_val)

Fungsi predict() digunakan untuk melakukan prediksi terhadap data validasi (X_val) menggunakan model yang telah dilatih sebelumnya.

In [ ]:
print("Accuracy:", accuracy_score(y_val, y_pred))

print("\nClassification Report:\n")

print(classification_report(y_val, y_pred))

Accuracy: 0.5232558139534884

Classification Report:

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         0
           4       0.08      0.33      0.13         3
           5       0.63      0.67      0.65        67
           6       0.55      0.46      0.50        78
           7       0.33      0.33      0.33        21
           8       0.50      0.33      0.40         3

    accuracy                           0.52       172
   macro avg       0.35      0.36      0.34       172
weighted avg       0.55      0.52      0.53       172

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Evaluasi model dilakukan menggunakan accuracy_score untuk mengukur tingkat akurasi prediksi model, serta classification_report untuk melihat performa model secara lebih rinci berdasarkan precision, recall, dan f1-score.

In [ ]:
model.fit(X, y)

DecisionTreeClassifier(class_weight='balanced', max_depth=10, random_state=42)

Setelah evaluasi selesai, model dilatih ulang menggunakan seluruh data training (X dan y) agar model dapat mempelajari pola data secara lebih lengkap sebelum digunakan untuk prediksi akhir pada data testing.

In [ ]:
test_pred = model.predict(test)

Fungsi predict() digunakan untuk memprediksi nilai kualitas wine pada data testing yang belum memiliki label target.

In [ ]:
submission = pd.DataFrame({
    'id': test_id,
    'quality': test_pred
})

Hasil prediksi disusun ke dalam sebuah DataFrame yang berisi kolom id dan quality agar sesuai dengan format file yang diminta.

In [ ]:
submission.to_csv('hasilprediksi_3NIM.csv', index=False)

Fungsi to_csv() digunakan untuk menyimpan hasil prediksi ke dalam file CSV

In [ ]:
submission.head()

     id  quality
0   222        5
1  1514        6
2   417        5
3   754        5
4   516        6

Fungsi submission.head() digunakan untuk menampilkan beberapa baris pertama hasil prediksi guna memastikan format data sudah benar sebelum dikumpulkan.

In [ ]:
from google.colab import files

files.download('hasilprediksi_3NIM.csv')

Fungsi files.download() digunakan untuk mengunduh file CSV hasil prediksi dari Google Colab ke perangkat agar dapat dikumpulkan.